import Head from "next/head";
import { useState } from "react";
import TextFieldDropdown from "../components/TextFieldDropdown/TextFieldDropdown";

export default function Home() {
  const [test, setTest] = useState("");

  return (
    <>
      <Head>
        <title>SearchTextboxWithDropdown</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex border border-dotted border-red-600">
        <div>
          <TextFieldDropdown
            dropdownValue={test}
            setDropdownValue={setTest}
            label="DropdownControlled"
            name="DropdownTest"
          />
        </div>
      </main>
      <div className="block px-4 py-2">
        <button onClick={() => console.log("dropdownData: ", test)} className="py-2 px-4 border border-black">Test</button>
      </div>
    </>
  );
}
